spring:
  datasource:
    username: root
    password: tcd
    url: jdbc:mysql://localhost:3306/testcontainers_demo
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: testcontainers-demo
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      use-new-id-generator-mappings: false
    open-in-view: false
    mapping-resources:
    generate-ddl: true
    show-sql: true
